### ISSUE TITLE
failed during stage 'building site'

### ISSUE THREAD

**Issue by illucent** [ryanwiemer/gatsby-starter-gcn#2]
failed to build with Netlify Deployment From Git (Recommended) method;
what it can be?

`failed during stage 'building site': Build script returned non-zero exit code: 1`
 ...

```
TypeError: Cannot read property 'allContentfulPost' of undefined
- gatsby-node.js:19 graphql.then.result
/opt/build/repo/gatsby-node.js:19:21
```

**Comment by ryanwiemer** [comment]
@illucent, I had to make some breaking changes last night as of `v1.0.0`. Could you try pulling down the latest version of the code and going through the `npm run setup` process to copy over the setup to a new blank space? 

Let me know if that resolves your issue.

Thanks,
Ryan

**Comment by illucent** [comment]
tried by installing everything locally  - same issue  - not resolved yet

**Comment by ryanwiemer** [comment]
@illucent Are you able to run `gatsby build` locally successfully? Or do you see the same error?

**Comment by illucent** [comment]
gatsby build

```
success delete html and css files from previous builds — 0.060 s
success open and validate gatsby-config.js — 0.067 s
success copy gatsby files — 0.286 s
success onPreBootstrap — 11.685 s
⠁ Starting to fetch data from Contentful
Fetching default locale
⢀ source and transform nodesdefault local is : en-US
⠄ source and transform nodescontentTypes fetched 6
Updated entries  16
Deleted entries  0
Updated assets  11
Deleted assets  0
Fetch Contentful data: 2084.961ms
success source and transform nodes — 2.365 s
success building schema — 0.824 s
success createLayouts — 0.210 s
success createPages — 0.083 s
success createPagesStatefully — 0.017 s
success onPreExtractQueries — 0.003 s
success update schema — 0.408 s
success extract queries from components — 0.345 s
success run graphql queries — 0.227 s
success write out page data — 0.004 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.001 s
info bootstrap finished - 78.789 s
success Building CSS — 12.699 s
error Generating JavaScript bundles failed
  Error: ./.cache/production
```

**Comment by ryanwiemer** [comment]
Hmmm interesting.  I am still not able to reproduce this and the error logging isn't super verbose so it's tough to debug. 

A few more questions to see if we can get to the bottom of your issue: 
- Is the space you created setup to use the `en-us` locale?
- Any errors in the console in develop mode?

If all else fails I may consider downgrading Gatsby to `v1.9.209`. There was some weird things happening that I logged an issue on the Gatsby repo. It was supposedly resolved but maybe there are still some errors.  https://github.com/gatsbyjs/gatsby/issues/4401

**Comment by illucent** [comment]
- Is the space you created setup to use the en-us locale?

yes

- Any errors in the console in develop mode?

```
success delete html and css files from previous builds — 0.009 s
success open and validate gatsby-config.js — 0.047 s
success copy gatsby files — 0.073 s
success onPreBootstrap — 2.522 s
⠁ Starting to fetch data from Contentful
Fetching default locale
⠁ source and transform nodesdefault local is : en-US
⠁ source and transform nodescontentTypes fetched 6
Updated entries  19
Deleted entries  0
Updated assets  16
Deleted assets  0
Fetch Contentful data: 2936.618ms
success source and transform nodes — 3.176 s
success building schema — 0.610 s
success createLayouts — 0.144 s
success createPages — 0.107 s
success createPagesStatefully — 0.023 s
success onPreExtractQueries — 0.003 s
success update schema — 0.321 s
success extract queries from components — 0.364 s
success run graphql queries — 0.257 s
success write out page data — 0.004 s
success write out redirect data — 0.000 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 23.444 s

error There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND


  Error: Module build failed: Error: Couldn't find preset "env" relative to directory "/home/illucent"
  
  - option-manager.js:293 
    [gatsby-starter-gcn]/[babel-core]/lib/transformation/file/options/option-manager.js:293:19
  
  - Array.map
  
  - option-manager.js:275 OptionManager.resolvePresets
    [gatsby-starter-gcn]/[babel-core]/lib/transformation/file/options/option-manager.js:275:20
  
  - option-manager.js:264 OptionManager.mergePresets
    [gatsby-starter-gcn]/[babel-core]/lib/transformation/file/options/option-manager.js:264:10
  
  - option-manager.js:249 OptionManager.mergeOptions
    [gatsby-starter-gcn]/[babel-core]/lib/transformation/file/options/option-manager.js:249:14
  
  - option-manager.js:368 OptionManager.init
    [gatsby-starter-gcn]/[babel-core]/lib/transformation/file/options/option-manager.js:368:12
  
  - index.js:212 File.initOptions
    [gatsby-starter-gcn]/[babel-core]/lib/transformation/file/index.js:212:65
  
  - index.js:135 new File
    [gatsby-starter-gcn]/[babel-core]/lib/transformation/file/index.js:135:24
  
  - pipeline.js:46 Pipeline.transform
    [gatsby-starter-gcn]/[babel-core]/lib/transformation/pipeline.js:46:16
  
  - index.js:46 transpile
    [gatsby-starter-gcn]/[babel-loader]/lib/index.js:46:20
  
  - fs-cache.js:79 
    [gatsby-starter-gcn]/[babel-loader]/lib/fs-cache.js:79:18
  
  - fs-cache.js:15 ReadFileContext.callback
    [gatsby-starter-gcn]/[babel-loader]/lib/fs-cache.js:15:14

```  
      
still same issue - i will try some another method

**Comment by illucent** [comment]
resolved by adding "contenful-export" package dependency

` "contentful-export": "^6.0.4",`
 
and modifying package.json at build stage

```
"build": "contentful-export
      --space-id $SPACE_ID
      --management-token $CONTENTFUL_MANAGEMENT_ACCESS_TOKEN
      --export-dir contentful/
      --content-file export.json && gatsby build",
```
this regenerates contentful content export json file to import by gatsby / netlify

**Comment by ryanwiemer** [comment]
@illucent, thank you for sharing what you did! 

For now I don't think I will make any changes to my starter template. But I am definitely looking for ways to streamline this process or at the very least make the README better! For the sake of clarity I thought I'd explain my thought process for local and remote builds in case that is helpful to you or anyone else. Sorry for the long response. Only read on if you are curious. 😉

---

In the initial `npm run setup` process the user enters their Contentful tokens and keys. This information is used to copy over the placeholder content into your blank space and to generate a file called `.contentful.json`. You can see a sample of what that looks like in [.contentful.json.sample](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/.contentful.json.sample). So for local development it is assumed that you have a `.contentful.json` file sitting in the root with the relevant keys filled in. 

Now for remote deployments on Netlify I added some rudimentary logic to the [gatsby-config.js](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/gatsby-config.js#L4-L13). This logic basically looks for the `.contenful.json` file and if it can't be found it uses the build environment variables `SPACE_ID` and `ACCESS_TOKEN` as noted in the README. So this requires that you have those setup in Netlify otherwise the site can't be built. 

So, with this project if you set up your Netlify site with the appropriate build environment variables  `gatsby build` run remotely on the Netlify server will be able to build a production version of the site. It shouldn't need to extract your whole Contentful setup every time you rebuild your site. Unless you have a specific requirement that I am unaware of that is not necessary and would add to your build time.  

Hopefully that helps you. If you have any other thoughts or ideas to make this repo better feel free to submit a PR or shoot me an email. 

Thanks!
