### ISSUE TITLE
Images Downloaded Twice on Mobile

### ISSUE THREAD

**Issue by brandonkal** [ryanwiemer/gatsby-starter-gcn#20]
I noticed this while remote debugging on Android Chrome. I am not sure why this is happening but it seems redundant and causes unnecessary HTTP requests.

On the index page of the site the card thumnails fetch and download images that have a width of 1200 pixels on my phone. However, after clicking into a post, the hero image is again downloaded, this time with a width of 900 pixels.

A prefferrable solution would be to only download the 900 pixel version for the card list or reuse the 1200 pixel image for the post pages.

On desktop, it makes sense to fetch the image twice. In my case, an 800 pixel wide image is fetched for the post listing cards and an 1800 pixel wide image is downloaded on the post pages.

However on mobile it seems silly to fetch the image twice especially when the post hero image is smaller than that of the card index.

**Comment by ryanwiemer** [comment]
@brandonkal, 

Okay, Interesting. 

On the [`index.js`](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/src/pages/index.js#L71) and [`tag.js`](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/src/templates/tag.js#L59) the hero image has a max width of 800px because the cards don't need a big image. On the [`post.js`](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/src/templates/post.js#L69) it has a larger max width of 1800px to accommodate the actual hero part of the page. 

Maybe we just set them all to use the same max width to avoid the "double download" in certain scenarios. A potential downside is possibly downloading a larger image then what is needed if all you do is look at the cards. I dunno. Might not be an issue. 

Why don't you try playing with the GraphQL queries to see if a certain max width produces better results or if we can avoid the double download. I am open to suggestions.

**Comment by brandonkal** [comment]
@ryanwiemer In my testing it seems Gatsby Image prefers to use clean multiples e.g. 900px wide when the max is set to 1800px though it is hard to tell if this is actual intelligence or coincidence. Perhaps that is why I got 900px images on the phone even though the query defaults to 800px. Not sure.

I suspect changing it all to a max size of 1800 would be best. I believe it will not download the full images on the index and tag pages on desktop.

Unfortunately I perhaps foolishly threw out the contentful space I was was using for the GCN template.
I've been building something based on GCN where hero images are optional but unfortunately this means I can no longer build from the GCN repo as it fails without an image attached to every post.

It will probably be quite some time before I can test this out.

---

On an unrelated note, do you experience font changes between `gatsby develop` and `gatsby build && gatsby serve`?

I've been working on typography a lot and for some reason when I run a build instead of using the `develop` command the browser ignores the `font-family` block and replaces all fonts with a serif font which was the cause of a lot of confusion.

I'm not sure if this has anything to do with the manifest.

**Comment by ryanwiemer** [comment]
This should be resolved in [`v1.2.1`](https://github.com/ryanwiemer/gatsby-starter-gcn/releases/tag/v1.2.1). The maxWidth is set to 1800 whenever using the heroImage.
