### ISSUE TITLE
Startup Readme Clarity?

### ISSUE THREAD

**Issue by lassiter** [ryanwiemer/gatsby-starter-gcn#24]
Ryan -- Thanks for creating this, it looks like a really cool project. I followed the setup instructions and it's still rendering your space via the export.json. I tried commenting it out but it's not loading my space. Can you provide some clarity on how I can start loading in my own content and adjusting the starter? I didn't see any issues with similar problems, I'm not sure what I'm missing. 😅 

It's building and I've received zero errors. I'm new to Gatsby and GraphQL, so I'm currently playing catchup.

**Comment by ryanwiemer** [comment]
@lassiter thank you for your interest in the repo!

If you follow the setup instructions by the end your previously blank Contenful space will now have an exact copy of the placeholder content and content model. From there you just add or remove entries in Contenful and then "rebuild" the site. You shouldn't need to touch the `export.json` file at anytime. That is there just so the template can grab the placeholder content via the setup process. 

Hopefully that helps. If you are still very new to Gatsby I would recommend reading up on the documentation as that will explain a lot of the core concepts. 

Thanks,
Ryan

**Comment by lassiter** [comment]
Got it, I didn't realize it would create new content types inside my Contentful Instance. If I'm wanting to adjust the content model to add things, I would just add that in the query in both the template and page while adjusting the internal props/return correct? (i.e. a Catagory in addition to "tags")

It does, I read through the docs a few months back and dropped my portfolio project -- I don't think it would hurt to reread the relevant parts.

Thanks for the quick response!

**Comment by ryanwiemer** [comment]
Yeah this assumes you have a specific content model.  If you want to change the content model you would need to change the relevant GraphQL queries and the corresponding components or files so that it knows what to pull from Contentful and how that data should be used or displayed. 

So for example let's say you wanted a subtitle that is used on the posts. You would do something similar to the following:

1. Create and save a new short text field called `subtitle` in the `post` content type in Contentful.
2. Make sure to use your new `subtitle` field in at least one post entry and save/publish in Contentful.  
3. Add `subtitle` to the GraphQL query in [`post.js`](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/src/templates/post.js) and use the data in some way such as placing it in an h2 tag or something. 
4. Rebuild the site and see your new subtitle field on the website. 

I would recommend starting with something very basic like that first so that you can get your feet wet. Creating a category is potentially a little more complicated since you probably want a page that displays all posts for a given category. For that you would need to also tweak the [gatsby-node.js](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/gatsby-node.js) file to generate those pages. 

Best of luck to you!

**Comment by ryanwiemer** [comment]
I'm going to close out. If there are any specific questions or issues related to this starter feel free to open a new issue.

**Comment by lassiter** [comment]
Thanks again!

**Comment by djnorrisdev** [comment]
Until I read this, I was all kinds of confused about the populating of data for the posts. I didn't realize when I went through setup that until I clicked something in contentful, it didn't show the data being populated from the starter into contentful.
