### ISSUE TITLE
Update to Gatsby V2

### ISSUE THREAD

**Issue by ryanwiemer** [ryanwiemer/gatsby-starter-gcn#30]
Waiting until Gatsby `v2` is officially launched but in the meantime starting work on migrating the code.

## List of issues/bugs with Gatsby v2
- ~~[[v2] Navigating to previously visited pages with Link retains scroll position](https://github.com/gatsbyjs/gatsby/issues/7454)~~
- ~~[[v2] [plugin-offline] Fetch is intercepted by Workbox unless we add ?no-cache=1](https://github.com/gatsbyjs/gatsby/issues/7997)~~

**Comment by ryanwiemer** [comment]
More testing needed but a new [`v2`](https://github.com/ryanwiemer/gatsby-starter-gcn/tree/v2) branch has been created with the migrated code.

**Comment by brandonkal** [comment]
Gatsby v2 is now out! @ryanwiemer let me know how I can help with this migration.

**Comment by ryanwiemer** [comment]
@brandonkal Thanks for the offer! I am pretty much good to go with [`v2`](https://github.com/ryanwiemer/gatsby-starter-gcn/tree/v2) but I'll let you know once it is officially released.

Here is a [demo](https://v2--gcn.netlify.com/).

I'm gonna give the [scroll position issue](https://github.com/gatsbyjs/gatsby/issues/7454) another day to see if that gets resolved and if not I can put in a temporary fix. I'd like to avoid that if possible though.

**Comment by brandonkal** [comment]
@ryanwiemer If I can make a suggestion, this page should be added to the Contentful model. Since v2 release will include a change of starter content, it would be nice if this was included as well.

It is a markdown reference post, which I found very useful to see all the typography and tweak the typography design when adapting this starter for my own site. For that reason, I believe it would be beneficial to include this as part of the starter to speed up development for others. I have made some changes to the original markdown reference in order to fit with the GCN starter design.

Since this is content, I can't really make a pull request for this, but the content of the post can be found here: https://gist.github.com/brandonkal/81aef71276a54536951c0f205797999c

**Comment by ryanwiemer** [comment]
Ahh Gotcha. Sure, I can add that in. Good suggestion.

**Comment by brandonkal** [comment]
Here is a potential image for the reference post: https://pxhere.com/en/photo/791258

**Comment by ryanwiemer** [comment]
The issues listed have now been resolved. I am going to merge `v2` into `master`.

@brandonkal - As for the updated markdown reference post I will add that in the near future. I need to add more styling to support that first.

**Comment by ryanwiemer** [comment]
Closed via https://github.com/ryanwiemer/gatsby-starter-gcn/pull/34 and released as [v2.0.0](https://github.com/ryanwiemer/gatsby-starter-gcn/releases/tag/v2.0.0)

**Comment by brandonkal** [comment]
@ryanwiemer I did some styling tweaks for that. I'll make a pull request.

**Comment by ryanwiemer** [comment]
@brandonkal sounds good!
