### ISSUE TITLE
Removing Tag Create Build Error

### ISSUE THREAD

**Issue by johnmeredith** [ryanwiemer/gatsby-starter-gcn#41]
Not sure if this is a bug or I need to RTFM but when removing tags from a previously publsihed post, I get the following build error on Netlify:

`TypeError: Cannot read property 'length' of null`

I tracked down my changes to me removing a tag from a post due to the post header looking too cramped (it's only one row and does not wrap?). 

I can recreate the error just by removing a tag from a post and re-publishing. 

In this example, I removed the tag `Norway` from [this post](https://archetextures.netlify.com/openehr-as-the-basis-for-a-data-warehouse/). I then get this build error:

[builderror.txt](https://github.com/ryanwiemer/gatsby-starter-gcn/files/2489403/builderror.txt)

If I add the tag back in it is fine again.

**Comment by ryanwiemer** [comment]
@johnmeredith, 

Thanks for logging the ticket. There appears to be two separate topics here:
1. CSS issue with the wrapping of tags (https://github.com/ryanwiemer/gatsby-starter-gcn/issues/42)
2. When you create a tag called `Norway` Contentful is actually making a new piece of content with the type of `tag`. That is how the tag pages are created. If `Norway` is no longer connected to any posts the build is failing because the `tag.js` template expects there to be posts. In order to solve this all tags need to be associated with at least one post. If you do not want to use that tag anymore you need to also delete the `Norway` tag content piece in Contentful. 

Let me know if that makes sense or if you have any other questions.

**Comment by johnmeredith** [comment]
No - that makes sense. I did as you just said and rmeoved Norway completly and it appear to have worked. Thank you - I'm both a Gatsby and Contentful newbie so learnign a lot today.  Embedding Disqus is my next task....!!

**Comment by ryanwiemer** [comment]
Cool. No worries. I'm gonna close out this ticket then.

**Comment by ryanwiemer** [comment]
Fixed in [2.0.2](https://github.com/ryanwiemer/gatsby-starter-gcn/releases/tag/2.0.2)

@johnmeredith, I added an extra check to make sure tags that do not contain any posts are ignored. They would still exists in Contentful but at least it will prevent the creation of orphaned tag pages or broken builds.
