### ISSUE TITLE
PageTitle.js

### ISSUE THREAD

**Issue by ghost** [ryanwiemer/gatsby-starter-gcn#46]
I am having a hard time figuring out the conditional(ternary) operator 'props.small'. It appears the condition is 'falsy'. 

Thanks for the starter.

**Comment by ryanwiemer** [comment]
@doakheggeness,

Thanks for using the starter. This sounds like more of a general usage question regarding React and styled-components. In the future it's best to keep that on something like stack overflow rather than this repo. 

With that said the`PageTitle.js` component has a boolean prop  called `small` and it is considered true if you include that prop when using the component. 

See: [`tag.js`](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/7f96a5d3479214ccfef505f0ee179f6985fb8ff0/src/templates/tag.js#L50) template.
