### ISSUE TITLE
Use blur up and progressive JPEGs

### ISSUE THREAD

**Issue by brandonkal** [ryanwiemer/gatsby-starter-gcn#5]
Not sure exactly how to implement this. The Contentful documentation mentions it is possible to force jpegs to be progressive but doesn't show how. I believe it is `?fl=progressive` though.

Also, using blur up for the hero images would probably make the transition less jarring. When I initially deployed the site to Netlify, the contentful images had a waiting time of 1.5 seconds.

**Comment by ryanwiemer** [comment]
@popwebz, 

That is actually very easy to do thanks to the [gatsby-image](https://www.gatsbyjs.org/packages/gatsby-image/?=images) plugin. The only reason I didn't use the blur up technique originally was due to personal preference. I may revisit that decision particularly for the hero images.

In the meantime if you would like to use the blur up technique simply change the following in your GraphQL query `...GatsbyContentfulSizes_withWebp_noBase64` → `...GatsbyContentfulSizes_withWebp`

Lastly remove `backgroundColor={'#eeeeee'}` from the desired `<Img/>` tag. And that's it!

As for progressive images the plugin may support that already but I'm not positive. I know for supporting browsers (Chrome) it uses [WebP images](https://developers.google.com/speed/webp/) which is an even more efficient/compressed format. 

For now I am going to close this ticket as I am not taking any action but thank you for the suggestions.

Thanks,
Ryan
