### ISSUE TITLE
.env file

### ISSUE THREAD

**Issue by blarsonmoore** [ryanwiemer/gatsby-starter-gcn#59]
I cloned this repo and successfully ran the setup and deployed to Netlify without any issues. However, when I clone the repo I created to a different computer I cannot find a .env file to add my Contentful space_id and access_token. I can hard code it into the gatsby-config.js but that is not ideal. Am I missing something?

**Comment by ryanwiemer** [comment]
@blarsonmoore That is due to the [`.gitignore`](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/.gitignore#L8) file. I would advise against committing your `.env` file or hardcoding passwords. 

So it does require taking the manual step of creating a new `.env` file on each of your computers. It's not ideal but it is more secure and that way you don't have your passwords accidentally committed to GitHub. 

Let me know if that makes sense. Best of luck!

**Comment by ryanwiemer** [comment]
Closing out this ticket. Let me know if you have any other questions.
