### ISSUE TITLE
After deleting provided posts, build fails

### ISSUE THREAD

**Issue by seoriam** [ryanwiemer/gatsby-starter-gcn#64]
Drafting, archiving, and deleting provided posts all lead to the below error log (trimmed for readability).
```
10:19:38 PM: Fetch Contentful data: 438.722ms
10:19:38 PM: success source and transform nodes — 0.563 s
10:19:39 PM: success building schema — 0.516 s
10:19:39 PM: success createPages — 0.065 s
10:19:39 PM: success createPagesStatefully — 0.050 s
10:19:39 PM: success onPreExtractQueries — 0.005 s
10:19:39 PM: success update schema — 0.034 s
10:19:39 PM: error GraphQL Error Encountered 1 error(s):
10:19:39 PM: - Unknown field 'metaDescription' on type 'ContentfulPost'.
10:19:39 PM:       file: /opt/build/repo/src/templates/post.js
10:19:39 PM: Skipping functions preparation step: no functions directory set
10:19:39 PM: Caching artifacts
```
Found that src/templates/post.js does contain metaDescription with default being the internal content. I've tried 'clear cache and deploy', 'deleting all related tags' to no avail. The only change I've made to Contentful was making 2 locales possible; below are my locale settings.

Locale | Fallback | Include in response | Editing | Required Fields
-- | -- | -- | -- | --
English - default | None | Enabled | Enabled | Content is required
Korean | English | Disabled | Enabled | Can be published empty

What might be causing the problem? Thank you very much for your help!

**Comment by seoriam** [comment]
After manually writing a meta description to an existing but custom post, the problem is gone. Still have no idea why the post didn't automatically use its content for the meta description. I've tested draft -> publish -> change on a new post and its working fine. @ryanwiemer May you please enlighten me on this?

**Comment by ryanwiemer** [comment]
@seoriam, 

It has to do with the way Gatsby infers the data structure and autogenerates the GraphQL schema at build time. If you have something in your graphQL query Gatsby expects there to be data and formatted a particular way. For this example there is a query for a metaDescription so Gatsby expects at least one otherwise the build fails. 

Please see the note on the [README](https://github.com/ryanwiemer/gatsby-starter-gcn#content-and-seo) regarding this topic. 

Gatsby is aware of this pain point and is working on solutions via [Schema Customization](https://www.gatsbyjs.org/blog/2019-03-18-releasing-new-schema-customization) to allow authors to define the expected data structure and prevent build failures even when the data doesn't exist. 

In the future I will look into adding schema customization but for now as long as you have at least one post, one tag and one meta description the build should work as expected.
