### ISSUE TITLE
Hot reload keeps refreshing

### ISSUE THREAD

**Issue by pvandriessche** [ryanwiemer/gatsby-starter-gcn#70]
Hi,

I just started with using you start for a gatsby/contentful blog.
I was able to set-up everythink fine but when I started to make minor change to the post and tag page I had some strange behavior.
The page keeps on refreshing continously as if the HRM keeps on finding a change to update for.
I'm using AWS C9 to code. 
I don't know if this error is related to gatsby or the AWS C9.

Any help or tips would be appreciated.

KR

**Comment by ryanwiemer** [comment]
@pvandriessche Hmmm I have never encountered that issues before. It sounds like it may be an issue specifically with your AWS C9 and Gatsby setup rather than this starter. 

I would recommend looking through the issues on https://github.com/gatsbyjs/gatsby/issues or maybe posting a question on Stack Overflow
