### ISSUE TITLE
Quick question for difference between two methods

### ISSUE THREAD

**Issue by ghost** [ryanwiemer/gatsby-starter-gcn#80]
Thank you for this great project, it is a great starter for people like me who are learning gatsby and react :)

I have a question about how how get variables from theme, 
what is the difference between using: 
```
${props => props.theme.colors.base}
```
and this one?

```
import theme from '../styles/theme'
${theme.colors.base}
```

They both get the base color from theme but what would be the main difference?

**Comment by ryanwiemer** [comment]
This project uses styled components which supports [theming](https://www.styled-components.com/docs/advanced#theming). 

**Scenario 1**
This is the normal way of using theme variables. It is possible because the theme variables are provided to the ThemeProvider in the  [`Layout`](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/src/components/Layout.js#L21) component.
```
${props => props.theme.colors.base}
```

**Scenario 2**
This a manual way of using theme variables. The only reason this exists in the codebase is because I wanted to use theme variables in [`GlobalStyle`](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/src/components/Layout.js#L30) which sits outside of the ThemeProvider 
```
import theme from '../styles/theme'
${theme.colors.base}
```

So for all intents and purposes you should use the syntax described for scenario 1.
