### ISSUE TITLE
new fields added to post model

### ISSUE THREAD

**Issue by SergeyRe** [ryanwiemer/gatsby-starter-gcn#97]
are not sown at GraphiQL schema.
Situation closed to described here
[possible bug? new contentful model field does not show up in graphql response](https://github.com/gatsbyjs/gatsby/issues/14160)
Meanwhile empty gatsby project with contentful plugin directed to the same space reproduce correct

**Comment by ryanwiemer** [comment]
@SergeyRe I'm not sure I understand what question you are asking.

If you want to add new fields you should be able to do that. Simply add the new field in Contentful, add the corresponding query on your site and it should be inferred and part of your GraphQL response. If it is not showing up you may need to regenerate the graphql snapshot since this starter uses [`gatsby-plugin-schema-snapshot`](https://www.gatsbyjs.org/packages/gatsby-plugin-schema-snapshot/?=snahp)

**Comment by SergeyRe** [comment]
Thanks for response
I overlooked this -sorry
I my case i decieded to exclude this plugin -something bad can happened?

**Comment by ryanwiemer** [comment]
Gotcha. No worries. It's fine to remove that plugin. I only included it as a way to "lock down" the expected fields so that even if the content didn't exist in Contentful the site would still be able to build. 

I am going to close out this ticket. Best of luck to you.

**Comment by DannyBoyNYC** [comment]
Hi Ryan and thanks for the useful template. We are using it to help those effected by the massive explosion in downtown Beruit. I ran into the exact problem above and, not being familiar with the snapshot plugin, spent quite a bit of time debugging before I saw this.You might consider adding a note about this in the readme.

**Comment by ryanwiemer** [comment]
Thanks for the feedback @DannyBoyNYC. I will definitely look at adding something to the readme to make it more clear. If you have any other questions or suggestions feel free to let me know.

And of course good luck on your project for a good cause. I’d love to see the final result. Send me a tweet or something when it launches https://mobile.twitter.com/ryanwiemer
